import type { Metadata } from "next";
import Navbar from "../components/Navbar";
import "./globals.css";
import type { Session } from "next-auth";
import { ToastContainer } from "react-toastify";
import { SessionProvider } from "next-auth/react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  session,
}: Readonly<{
  children: React.ReactNode;
  session: Session | null;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <SessionProvider session={session}>
          <Navbar />
          <ToastContainer />
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}
