import type { Metadata } from "next";
import Navbar from "../components/Navbar";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import { SessionProvider } from "next-auth/react"
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <SessionProvider>
        <Navbar />
        <ToastContainer />
        {children}
        </SessionProvider>
      </body>
    </html>
  );
}
