import type { Metadata } from "next";
import Navbar from "@/src/components/Navbar";
import "../globals.css";
import { ToastContainer } from "react-toastify";
import { SessionProvider } from "next-auth/react";
export const metadata: Metadata = {
  title: "Foodie",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <SessionProvider >
          <Navbar />
          <ToastContainer autoClose={2000} />
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}
